ALTER SESSION SET CONTAINER = FREEPDB1;

CONNECT admin/admin@//localhost:1521/FREEPDB1

CREATE TABLE PROPERTIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 77) PRIMARY KEY,
    APPLICATION VARCHAR2(255) NOT NULL,
    PROFILE VARCHAR2(255) NOT NULL,
    LABEL VARCHAR2(255) DEFAULT 'latest',
    KEY VARCHAR2(255) NOT NULL,
    VALUE VARCHAR2(4000) NOT NULL
);


Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (1,'application','default','latest','management.endpoints.web.exposure.include','*');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (2,'application','default','latest','management.endpoint.health.show-details','always');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (3,'application','default','latest','spring.datasource.driver-class-name','oracle.jdbc.OracleDriver');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (4,'application','default','latest','spring.datasource.url','jdbc:oracle:thin:@//oracleDB:1521/FREEPDB1');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (5,'application','default','latest','spring.datasource.username','admin');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (6,'application','default','latest','spring.datasource.password','admin');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (7,'application','default','latest','spring.jpa.hibernate.ddl-auto','update');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (8,'application','default','latest','eureka.client.register-with-eureka','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (9,'application','default','latest','eureka.client.fetch-registry','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (10,'application','default','latest','eureka.client.service-url.defaultZone','http://DiscoveryService:8761/eureka/');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (11,'Exam-Service','default','latest','server.port','8085');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (12,'Question-Service','default','latest','server.port','8084');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (13,'Student-Service','default','latest','server.port','8083');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (14,'User-Management-System','default','latest','server.port','8081');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (15,'Gateway-Service','default','latest','server.port','8443');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (16,'Gateway-Service','default','latest','spring.security.user.name','admin');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (17,'Gateway-Service','default','latest','spring.security.user.password','Admin@123');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (18,'Notification-Service','default','latest','server.port','8082');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (19,'Notification-Service','default','latest','spring.mail.host','smtp.gmail.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (20,'Notification-Service','default','latest','spring.mail.port','587');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (21,'Notification-Service','default','latest','spring.mail.username','no.reply.learning.college@gmail.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (22,'College-Management','dev','latest','server.port','8080');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (23,'College-Management','dev','latest','activeProfile','Dev profiles is activated');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (24,'College-Management','prod','latest','server.port','8080');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (25,'College-Management','prod','latest','activeProfile','Prod profiles is activated');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (26,'Gateway-Service','default','latest','spring.security.oauth2.client.registration.google.client-id','92202291958-98rm54v2tv39v5bt9nho7sslnfl6slpa.apps.googleusercontent.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (27,'Gateway-Service','default','latest','spring.security.oauth2.client.registration.google.client-secret','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');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (28,'Notification-Service','default','latest','spring.mail.password','clgjwgaybofnegnt');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (29,'Notification-Service','default','latest','spring.mail.properties.mail.smtp.auth','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (30,'Notification-Service','default','latest','spring.mail.properties.mail.smtp.starttls.enable','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (31,'Exam-Service','default','latest','resilience4j.circuitbreaker.instances.questionServiceCB.sliding-window-size','10');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (32,'Exam-Service','default','latest','resilience4j.circuitbreaker.instances.questionServiceCB.failure-rate-threshold','50');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (33,'Exam-Service','default','latest','resilience4j.circuitbreaker.instances.questionServiceCB.wait-duration-in-open-state','10000ms');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (34,'UsersManagementSystem','default','latest','resilience4j.retry.instances.notificationServiceRetry.max-attempts','3');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (35,'UsersManagementSystem','default','latest','resilience4j.retry.instances.notificationServiceRetry.wait-duration','2000ms');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (36,'Exam-Service','default','latest','resilience4j.ratelimiter.instances.examRateLimiter.limit-for-period','10');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (37,'Exam-Service','default','latest','resilience4j.ratelimiter.instances.examRateLimiter.limit-refresh-period','300s');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (38,'Exam-Service','default','latest','resilience4j.ratelimiter.instances.examRateLimiter.timeout-duration','0ms');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (39,'Exam-Service','default','latest','resilience4j.bulkhead.instances.examBulkhead.max-concurrent-calls','5');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (40,'Exam-Service','default','latest','resilience4j.bulkhead.instances.examBulkhead.max-wait-duration','0ms');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (41,'Exam-Service','default','latest','management.zipkin.tracing.endpoint','http://zipkin:9411/api/v2/spans');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (42,'Exam-Service','default','latest','management.tracing.sampling.probability','1.0');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (43,'Exam-Service','default','latest','logging.pattern.level','%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (44,'Gateway-Service','default','latest','management.zipkin.tracing.endpoint','http://zipkin:9411/api/v2/spans');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (45,'Gateway-Service','default','latest','management.tracing.sampling.probability','1.0');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (46,'Gateway-Service','default','latest','logging.pattern.level','%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (47,'Question-Service','default','latest','management.zipkin.tracing.endpoint','http://zipkin:9411/api/v2/spans');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (48,'Question-Service','default','latest','management.tracing.sampling.probability','1.0');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (49,'Question-Service','default','latest','logging.pattern.level','%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (50,'Exam-Service','default','latest','management.tracing.enabled','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (51,'Gateway-Service','default','latest','management.tracing.enabled','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (52,'Question-Service','default','latest','management.tracing.enabled','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (61,'College-Management','dev','latest','spring.kafka.producer.bootstrap-servers','kafka:19092');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (62,'College-Management','dev','latest','spring.kafka.producer.key-serializer','org.apache.kafka.common.serialization.StringSerializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (63,'College-Management','dev','latest','spring.kafka.producer.value-serializer','org.springframework.kafka.support.serializer.JsonSerializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (64,'College-Management','prod','latest','spring.kafka.producer.bootstrap-servers','kafka:19092');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (65,'College-Management','prod','latest','spring.kafka.producer.key-serializer','org.apache.kafka.common.serialization.StringSerializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (66,'College-Management','prod','latest','spring.kafka.producer.value-serializer','org.springframework.kafka.support.serializer.JsonSerializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (67,'Notification-Service','default','latest','spring.kafka.consumer.bootstrap-servers','kafka:19092');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (68,'Notification-Service','default','latest','spring.kafka.consumer.group-id','notification-group');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (69,'Notification-Service','default','latest','spring.kafka.consumer.key-deserializer','org.apache.kafka.common.serialization.StringDeserializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (70,'Notification-Service','default','latest','spring.kafka.consumer.value-deserializer','org.springframework.kafka.support.serializer.JsonDeserializer');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (71,'Notification-Service','default','latest','spring.kafka.consumer.properties.spring.json.trusted.packages','*');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (72,'Notification-Service','default','latest','spring.kafka.consumer.properties.spring.json.use.type.headers','false');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (73,'Notification-Service','default','latest','spring.kafka.consumer.properties.spring.json.value.default.type','com.learning.college.NotificationService.dto.Notification');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (75,'application','default','latest','logging.logback.rollingpolicy.max-file-size','10MB');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (76,'application','default','latest','logging.logback.rollingpolicy.max-history','7');

COMMIT;
