REM INSERTING into PROPERTIES
SET DEFINE OFF;
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (1,'application','default','latest','management.endpoints.web.exposure.include','*');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (2,'application','default','latest','management.endpoint.health.show-details','always');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (3,'application','default','latest','spring.datasource.driver-class-name','oracle.jdbc.OracleDriver');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (4,'application','default','latest','spring.datasource.url','jdbc:oracle:thin:@//localhost:1521/XEPDB1');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (5,'application','default','latest','spring.datasource.username','SYSTEM');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (6,'application','default','latest','spring.datasource.password','Sana@1999');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (7,'application','default','latest','spring.jpa.hibernate.ddl-auto','update');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (8,'application','default','latest','eureka.client.register-with-eureka','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (9,'application','default','latest','eureka.client.fetch-registry','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (10,'application','default','latest','eureka.client.service-url.defaultZone','http://localhost:8761/eureka/');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (11,'Exam-Service','default','latest','server.port','8085');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (12,'Question-Service','default','latest','server.port','8084');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (13,'Student-Service','default','latest','server.port','8083');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (14,'User-Management-System','default','latest','server.port','8081');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (15,'Gateway-Service','default','latest','server.port','8443');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (16,'Gateway-Service','default','latest','spring.security.user.name','admin');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (17,'Gateway-Service','default','latest','spring.security.user.password','Admin@123');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (18,'Notification-Service','default','latest','server.port','8082');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (19,'Notification-Service','default','latest','spring.mail.host','smtp.gmail.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (20,'Notification-Service','default','latest','spring.mail.port','587');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (21,'Notification-Service','default','latest','spring.mail.username','no.reply.learning.college@gmail.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (22,'College-Management','dev','latest','server.port','8080');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (23,'College-Management','dev','latest','activeProfile','Dev profiles is activated');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (24,'College-Management','prod','latest','server.port','8080');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (25,'College-Management','prod','latest','activeProfile','Prod profiles is activated');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (26,'Gateway-Service','default','latest','spring.security.oauth2.client.registration.google.client-id','92202291958-98rm54v2tv39v5bt9nho7sslnfl6slpa.apps.googleusercontent.com');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (27,'Gateway-Service','default','latest','spring.security.oauth2.client.registration.google.client-secret','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');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (28,'Notification-Service','default','latest','spring.mail.password','clgjwgaybofnegnt');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (29,'Notification-Service','default','latest','spring.mail.properties.mail.smtp.auth','true');
Insert into PROPERTIES (ID,APPLICATION,PROFILE,LABEL,KEY,VALUE) values (30,'Notification-Service','default','latest','spring.mail.properties.mail.smtp.starttls.enable','true');
commit;