spring.application.name=College-Management

spring.config.import=optional:configserver:http://config-server:8888

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost

spring.profiles.active=dev

#server.port=8080

kafka.bootstrap-server=kafka:19092
