spring.application.name=Config-Server

server.port=8888

# Set active profile to JDBC (Database backend)
spring.profiles.active=jdbc

# Oracle Datasource connection details
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//oracleDB:1521/FREEPDB1
spring.datasource.username=admin
spring.datasource.password=admin

# Eureka Settings
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.hostname=config-server

spring.cloud.config.server.jdbc.default-label=latest

#logging.file.name=/app/logs/${spring.application.name}.log
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.max-history=7