spring.application.name=Exam-Service

#server.port=8085
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
#spring.datasource.username=SYSTEM
#spring.datasource.password=Sana@1999
#spring.jpa.hibernate.ddl-auto=update
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost


spring.config.import=optional:configserver:http://config-server:8888