spring.application.name=Notification-Service

spring.config.import=optional:configserver:http://ConfigServer:8888

#
#server.port=8082
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
#spring.datasource.username=SYSTEM
#spring.datasource.password=Sana@1999
#spring.jpa.hibernate.ddl-auto=update
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost
#
#spring.mail.properties[mail.smtp.connectiontimeout]=5000
#spring.mail.properties[mail.smtp.timeout]=3000
#spring.mail.properties[mail.smtp.writetimeout]=5000
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.protocol=smtp
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=no.reply.learning.college@gmail.com
#spring.mail.password=clgjwgaybofnegnt