spring.application.name=Discovery-Service

server.port=8761

eureka.client.register-with-eureka=false 
eureka.client.fetch-registry=false

eureka.instance.hostname=DiscoveryService

spring.cloud.config.server.jdbc.default-label=latest

#logging.file.name=/app/logs/${spring.application.name}.log
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.max-history=7