spring.application.name=Gateway-Service

#server.port=8443
#
## Connect to the DiscoveryService (Eureka) running on 8761
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost
#
## Static Basic Auth properties for your gateway security testing
#spring.security.user.name=admin
#spring.security.user.password=Admin@123
#
#spring.security.oauth2.client.registration.google.client-id=92202291958-98rm54v2tv39v5bt9nho7sslnfl6slpa.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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

spring.config.import=optional:configserver:http://ConfigServer:8888